In [3]:
import pandas as pd
import numpy as np

In [5]:
pd.set_option('display.max_rows', 25)
pd.set_option('display.max_columns', None)

# Turn files into csv

In [1]:
import csv

# Open the input and output files
with open('./Data/train.txt', 'r') as input_file, open('./Data/train.csv', 'w', newline='') as output_file:
    
    # Create a CSV writer object
    csv_writer = csv.writer(output_file)
    
    # Read the input file in chunks
    while True:
        chunk = input_file.readline()
        if not chunk:
            break
        
        # Split the chunk into fields (assuming tab-separated values)
        fields = chunk.strip().split('\t')
        
        # Write the fields to the output file as a CSV row
        csv_writer.writerow(fields)

In [ ]:
import os, sys

usage_string = 'usage: txt2csv.py {tr|te} input output'

if len(sys.argv) != 4:
    print(usage_string)
    exit(1)

type, src_path, dst_path = sys.argv[1:]

if type == 'tr':
    header = 'Id,Label,I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,I11,I12,I13,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,C15,C16,C17,C18,C19,C20,C21,C22,C23,C24,C25,C26' 
    idx = 10000000
elif type == 'te':
    header = 'Id,I1,I2,I3,I4,I5,I6,I7,I8,I9,I10,I11,I12,I13,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12,C13,C14,C15,C16,C17,C18,C19,C20,C21,C22,C23,C24,C25,C26' 
    idx = 60000000
else:
    print(usage_string)
    exit(1)

with open(dst_path, 'w') as f:
    f.write(header + '\r\n')
    for line in open(src_path, 'r'):
        line = str(idx) + ',' + line.replace('\t', ',')
        f.write(line.replace('\n', '\r\n'))
        idx += 1

In [14]:
columns_name = ['id', 'click', 'hour', 'C1', 'banner_pos', 'site_id', 'site_domain', 'site_category', 'app_id', 'app_domain', 'app_category', 'device_id', 'device_ip', 'device_model', 'device_type', 'device_conn_type', 'C14', 'C15', 'C16', 'C17', 'C18', 'C19', 'C20', 'C21', 'weekday', 'hour_of_day']

In [15]:
len(columns_name)

26

In [17]:
# Set the batch size
batch_size = 10000

# Create a CSV iterator object
csv_iterator = pd.read_csv('./Data/train.csv', chunksize=batch_size)

# Iterate over the batches of data
for batch in csv_iterator:
    display(batch.head())
    break

,0,1,1.1,5,0.1,1382,4,15,2,181,1.2,2.1,Unnamed: 12,2.2,68fd1e64,80e26c9b,fb936136,7b4723c4,25c83c98,7e0ccccf,de7995b8,1f89b562,a73ee510,a8cd5504,b2cb9c98,37c9c164,2824a5f6,1adce6ef,8ba8b39a,891b62e7,e5ba7672,f54016b9,21ddcdc9,b1252a9d,07b5194c,Unnamed: 35,3a171ecb,c5c50484,e8b83407,9727dd16
0,0,2.0,0,44.0,1.0,102.0,8.0,2.0,2.0,4.0,1.0,1.0,NaN,4.0,68fd1e64,f0cf0024,6f67f7e5,41274cd7,25c83c98,fe6b92e5,922afcc0,0b153874,a73ee510,2b53e5fb,4f1b46f3,623049e6,d7020589,b28479f6,e6c5b5cd,c92f3b61,07c540c4,b04e4670,21ddcdc9,5840adea,60f6221e,NaN,3a171ecb,43f13e8b,e8b83407,731c3655
1,0,2.0,0,1.0,14.0,767.0,89.0,4.0,2.0,245.0,1.0,3.0,3.0,45.0,287e684f,0a519c5c,02cf9876,c18be181,25c83c98,7e0ccccf,c78204a1,0b153874,a73ee510,3b08e48b,5f5e6091,8fe001f4,aa655a2f,07d13a8f,6dc710ed,36103458,8efede7f,3412118d,NaN,NaN,e587c466,ad3062eb,3a171ecb,3b183c5c,NaN,NaN
2,0,NaN,893,NaN,NaN,4392.0,NaN,0.0,0.0,0.0,NaN,0.0,NaN,NaN,68fd1e64,2c16a946,a9a87e68,2e17d6f6,25c83c98,fe6b92e5,2e8a689b,0b153874,a73ee510,efea433b,e51ddf94,a30567ca,3516f6e6,07d13a8f,18231224,52b8680f,1e88c74f,74ef3502,NaN,NaN,6b3a5ca6,NaN,3a171ecb,9117a34a,NaN,NaN
3,0,3.0,-1,NaN,0.0,2.0,0.0,3.0,0.0,0.0,1.0,1.0,NaN,0.0,8cf07265,ae46a29d,c81688bb,f922efad,25c83c98,13718bbd,ad9fa255,0b153874,a73ee510,5282c137,e5d8af57,66a76a26,f06c53ac,1adce6ef,8ff4b403,01adbab4,1e88c74f,26b3c7a7,NaN,NaN,21c9516a,NaN,32c7478e,b34f3128,NaN,NaN
4,0,NaN,-1,NaN,NaN,12824.0,NaN,0.0,0.0,6.0,NaN,0.0,NaN,NaN,05db9164,6c9c9cf3,2730ec9c,5400db8b,43b19349,6f6d9be8,53b5f978,0b153874,a73ee510,3b08e48b,91e8fc27,be45b877,9ff13f22,07d13a8f,06969a20,9bc7fff5,776ce399,92555263,NaN,NaN,242bb710,8ec974f4,be7c41b4,72c78f11,NaN,NaN